### ISSUE TITLE
Chairs not working in 3.9 with Spigot 1.8

### ISSUE THREAD

**Issue by LadyCailinBot** [EngineHub/CraftBook#931]
CRAFTBOOK-3082 - Reported by seriosbrad

[04:57:29] [Server thread/INFO]: [CraftBook] Enabling CraftBook v3.9-SNAPSHOT
[04:57:29] [Server thread/INFO]: [CraftBook] Loading persistent data from YAML!
[04:57:29] [Server thread/WARN]: [CraftBook] Failed to load mechanic: Chairs
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.7.0_71]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585) ~[?:1.7.0_71]
	at java.lang.Class.getConstructor0(Class.java:2885) ~[?:1.7.0_71]
	at java.lang.Class.newInstance(Class.java:350) ~[?:1.7.0_71]
	at com.sk89q.craftbook.bukkit.CraftBookPlugin.setupCraftBook(CraftBookPlugin.java:568) [CraftBook.jar:3.9-SNAPSHOT]
	at com.sk89q.craftbook.bukkit.CraftBookPlugin.onEnable(CraftBookPlugin.java:434) [CraftBook.jar:3.9-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:744) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:631) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-b43a31a-20c65ca]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_71]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_71]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-b43a31a-20c65ca]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-b43a31a-20c65ca]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_71]
	... 22 more

**Comment by me4502** [comment]
Missing ProtocolLib
